language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
#env:
#  - ARCH=i386
#  - ARCH=x64
#  - ARCH=arm
notifications:
  email:
    recipients:
      - zhukov@oriense.com
      - yagubova@oriense.com
    on_success: change #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
before_install: # Use this to prepare the system to install prerequisites or dependencies
 
install: # Use this to install any prerequisites or dependencies necessary to run your build
  - sudo apt-add-repository ppa:ubuntu-sdk-team/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libopencv-dev
  - sudo apt-get install -qq qt5-default libqt5svg5-dev

before_script: # Use this to prepare your build for testing e.g. copy database configurations, environment variables, etc.
  - cmake -D WITH_BIOMETRICS=ON -D WITH_AR=ON . 

script: # All commands must exit with code 0 on success. Anything else is considered failure.
  - make -i
